Initial draft for standalone Vault Plugin installation
opencredo/vault-plugin-database-redis-enterprise pull request #2
Opened 2021-02-11 14:00 UTC by trentrosenbaum

This is an initial draft of the vault standalone instructions based on the Vault Plugin page for the Oracle plugin.  The page assumes the Redis Enterprise plugin is available in the Vault catalog and then presents a series of commands that will allow the plugin to be setup and used to generate an dynamic credential to verify the setup.

The commands have been run locally against vault in dev mode and against a running cluster.  The vault instance was local and not the container provisioned in the docker compose file.

2021-02-15 16:18 UTC, wjam commented on docs/vault-deployment.md
> +(see [Rotate Root Credentials] (/api-docs/secret/databases#rotate-root-credentials)).
Space should be deleted to make this a link

2021-02-15 16:19 UTC, wjam requested changes
Need space removed to fix the link

2021-02-15 17:04 UTC, trentrosenbaum commented on docs/vault-deployment.md
> +(see [Rotate Root Credentials] (/api-docs/secret/databases#rotate-root-credentials)).
Updated to remove the space.

2021-02-16 08:18 UTC, wjam commented on docs/vault-deployment.md
> +(see [Rotate Root Credentials](/api-docs/secret/databases#rotate-root-credentials)).
This URL should probably be the absolute URL rather than a relative one

2021-02-16 12:34 UTC, wjam commented on docs/vault-deployment.md
> +
```suggestion
**Note**: As Redis Enterprise does not support automatically expiring the users created for a dynamic credential, these users may still be active if Vault is unable to communicate with Redis Enterprise when the leased secret expires as the plugin will be unable to delete the users. You can attempt to manually revoke the leased secret by using the `vault lease revoke <lease_id>`, where the `<lease_id>` will appear in the Vault logs like `2021-02-03T10:43:47.943Z [ERROR] expiration: maximum revoke attempts reached: lease_id=database/creds/mydb/cpXGOg2hJ6uE0OWJXphXhLth`. A newly elected Vault HA leader will automatically attempt to any leases that have expired but haven't yet been deleted, so will try to delete the user again.
```

Should probably mention about how Vault/Redis would handle a network partition

2021-02-16 12:37 UTC, wjam commented on docs/vault-deployment.md
> +(see [Rotate Root Credentials](/api-docs/secret/databases#rotate-root-credentials)).
```suggestion
(see [Rotate Root Credentials](https://www.vaultproject.io/api/secret/databases#rotate-root-credentials)). 
```

2021-02-18 08:37 UTC, wjam commented on docs/k8s-deployment.md
> +$ export VERSION=`curl --silent https://api.github.com/repos/RedisLabs/redis-enterprise-k8s-docs/releases/latest | grep tag_name | awk -F'"' '{print $4}'`
Probably clearer to just use `jq` as it's already a requirement listed above

2021-02-18 08:47 UTC, wjam commented on docs/k8s-deployment.md
> +Active
Nitpick: should be `active`

2021-02-18 08:47 UTC, wjam commented on docs/k8s-deployment.md
> +$ make test-acc
`test-acc` no longer exists - there is only `test`

2021-02-18 08:50 UTC, wjam commented on docs/k8s-deployment.md
> +      emptyDir: {}
Use of emptyDir means that the contents will disappear when the pod gets rescheduled on a different node

2021-02-18 08:53 UTC, wjam commented
A few comments and also the PR should be raised against https://github.com/RedisLabs/vault-plugin-database-redis-enterprise

2021-02-18 09:21 UTC, wjam commented on docs/k8s-deployment.md
> +$ vault write database/config/redis-mydb plugin_name="redisenterprise-database-plugin" url="https://external-access.default.svc.cluster.local:9443" allowed_roles="*" database=mydb username=<PROVISION
Remind people to create a _new_ user before configuring Vault

2021-02-18 09:24 UTC, wjam commented on docs/k8s-deployment.md
> +After the Vault instance has been unsealed the Redis Enterprise Vault Plugin can be installed.  Firstly the plugin binary is built
This might need to be updated once goreleaser has pushed a release, to download the actual release?

2021-02-18 09:26 UTC, wjam commented on docs/k8s-deployment.md
> +### Testing Cluster with Vault Plugin Tests
This section should be in the main README

2021-02-18 09:27 UTC, wjam commented on docs/k8s-deployment.md
> +### Vault
Add comment indicating the user may want to build their own image in the long term

2022-07-21 14:38 UTC, closed without merging